plugins:
  - jest
  - babel
env:
  node: true
  es2021: true
  jest: true
  browser: true

parser: '@babel/eslint-parser'

extends:
  - airbnb-base
  - eslint:recommended
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
  requireConfigFile: false
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  object-curly-newline:
    - 0
  no-param-reassign: ['error', { 'props': false }]
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  brace-style:
    - off
  # arrow-body-style:
  #   - off
  # no-shadow:
  #   - off
  # operator-linebreak:
  #   ['error', 'after', { 'overrides': { '?': 'before', ':': 'before' } }]
  import/extensions:
    - error
    - ignorePackages
    - js: always
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
